# Copyright 2020 ETH Zurich and University of Bologna.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Samuel Riedel, ETH Zurich

variables:
  GIT_SUBMODULE_STRATEGY: none
  ROOT_DIR: '$CI_PROJECT_DIR'
  APPS: "tests"
  RUST_LOG: 'memora=debug'
  PATH: '/home/gitlabci/.cargo/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/condor/bin:/usr/sepp/bin'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME

before_script:
  - env

stages:
  - build
  - compiler
  - test

tc-gcc:
  stage: build
  script:
    - |
      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup tc-riscv-gcc; then
        git submodule update --init --recursive -- toolchain/riscv-gnu-toolchain
        make tc-riscv-gcc
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert tc-riscv-gcc
      fi

tc-llvm:
  stage: build
  script:
    - |
      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup tc-llvm; then
        git submodule update --init --recursive -- toolchain/llvm-project
        make tc-llvm
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert tc-llvm
      fi

riscv-isa-sim:
  stage: build
  script:
    - |
      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup riscv-isa-sim; then
        git submodule update --init --recursive -- toolchain/riscv-isa-sim
        make riscv-isa-sim
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert riscv-isa-sim
      fi

halide:
  stage: compiler
  script:
    - |
      if ! $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh lookup halide; then
        # Download LLVM
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-llvm
        # Build Halide
        git submodule update --init --recursive -- toolchain/halide
        make halide
        $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh insert halide
      fi
  needs: ["tc-llvm"]

hardware:
  stage: test
  script:
    - make -C hardware
  needs: []

# Software tests
.apps: &apps-job-anchor
  stage: test
  artifacts:
    paths:
      - hardware/build/transcript
      - hardware/build/trace_hart_*.trace
      - hardware/results

.apps_script:
  script: &apps-script-anchor
    - cd apps
    - |
      for APP in ${APPS}; do
        make COMPILER=${COMPILER} bin/${APP}
      done
    - cd ../hardware
    - |
      for APP in ${APPS}; do
        app=${APP} make simc
      done

apps-llvm:
  <<: *apps-job-anchor
  script:
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get riscv-isa-sim
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-llvm
    - *apps-script-anchor
  variables:
    COMPILER: "llvm"
  needs: ["tc-gcc","riscv-isa-sim","tc-llvm"]

apps-gcc:
  <<: *apps-job-anchor
  script:
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-riscv-gcc
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get riscv-isa-sim
    - *apps-script-anchor
  variables:
    COMPILER: "gcc"
  needs: ["tc-gcc","riscv-isa-sim"]

# Unit tests
unit-tests:
  stage: test
  script:
    - make test
  variables:
    GIT_SUBMODULE_STRATEGY: none
  needs: ["tc-gcc","tc-isa-sim"]
  dependencies:
    - tc-gcc
    - tc-isa-sim
  artifacts:
    paths:
      - apps/riscv-tests/isa/*.dump
      - apps/riscv-tests/isa/*.out32
      - apps/bin/*.dump
      - hardware/build/transcript
      - hardware/results

# Code style test
code-style:
  stage: test
  script:
    # Download LLVM
    - $CI_PROJECT_DIR/.gitlab-ci.d/memora_retry.sh get tc-llvm
    - ./.gitlab-ci.d/lint.sh
  needs: ["tc-llvm"]
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      allow_failure: false
    - if: '$CI_MERGE_REQUEST_ID == null'
      allow_failure: true
