# Copyright 2019 ETH Zurich and University of Bologna.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Samuel Riedel, ETH Zurich

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ROOT_DIR: '$CI_PROJECT_DIR'

before_script:
  - env

after_script:
  - env

stages:
  - build
  - compiler
  - test

tc-gcc:
  stage: build
  script:
    - git submodule update --init --recursive -- toolchain/riscv-gnu-toolchain
    - make tc-riscv-gcc
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    paths:
      - install/riscv-gcc
    expire_in: 1 day

tc-llvm:
  stage: build
  script:
    - git submodule update --init --recursive -- toolchain/llvm-project
    - make tc-llvm
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    paths:
      - install/llvm
    expire_in: 1 day

tc-isa-sim:
  stage: build
  script:
    - git submodule update --init --recursive -- toolchain/riscv-isa-sim
    - make riscv-isa-sim
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    paths:
      - install/riscv-isa-sim
    expire_in: 1 day

halide:
  stage: compiler
  script:
    - git submodule update --init --recursive -- toolchain/halide
    - make halide
  artifacts:
    paths:
      - install/halide
    expire_in: 1 day
  variables:
    GIT_SUBMODULE_STRATEGY: none
  needs: ["tc-llvm"]
  dependencies:
    - tc-llvm

hardware:
  stage: test
  script:
    - make -C hardware
  variables:
    GIT_SUBMODULE_STRATEGY: none
  needs: []
  dependencies: []

apps-llvm:
  stage: test
  script:
    - cd apps
    - make bin/hello_world
    - cd ../hardware
    - app=hello_world make run
    - make trace
  artifacts:
    paths:
      - hardware/build/transcript
      - hardware/build/trace_hart_*.trace
  variables:
    GIT_SUBMODULE_STRATEGY: none
  needs: ["tc-gcc","tc-llvm","tc-isa-sim"]
  dependencies:
    - tc-gcc
    - tc-llvm
    - tc-isa-sim

apps-gcc:
  stage: test
  script:
    - cd apps
    - make COMPILER=gcc bin/matrix_mul
    - cd ../hardware
    - app=matrix_mul make run
    - make trace
  artifacts:
    paths:
      - hardware/build/transcript
      - hardware/build/trace_hart_*.trace
  variables:
    GIT_SUBMODULE_STRATEGY: none
  needs: ["tc-gcc","tc-isa-sim"]
  dependencies:
    - tc-gcc
    - tc-isa-sim
